[package]
name = "word-filter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
overlay-db = { path = "../overlay-db" }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
