[package]
name = "image-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image = "0.25"
ab_glyph = "0.2"
imageproc = "0.25"
qrcode = "0.14"
chrono = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
