[package]
name = "image-processor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image = "0.25"
tracing = { workspace = true }
thiserror = { workspace = true }
