name: test

on:
  pull_request:
    branches: [develop]

jobs:
  test-crates:
    runs-on: ubuntu-latest
    env:
      DRY_RUN_MODE: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test library crates
        run: |
          cargo test -p overlay-db
          cargo test -p image-engine
          cargo test -p catprinter
          cargo test -p twitch-client
          cargo test -p word-filter
